apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-rabbitmq-repo
spec:
  fetch:
    imgpkgBundle:
      image: kind-registry.local:5000/p-rabbitmq-for-kubernetes/tanzu-rabbitmq-package-repo:1.5.3-nocompression
