apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-downstream-1-secret
  namespace: rabbitmq-system # Changeme
type: Opaque
stringData:
  username: replicator  # Changeme
  password: Lowerc@ase1 # Changeme
