apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-upstream-1-secret
  namespace: rabbitmq-system # Changeme
type: Opaque
stringData:
  username: replicator  # Changeme
  password: Lowerc@ase1 # Changeme
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-1-upstream-replicator
  namespace: rabbitmq-system # Changeme
spec:
  rabbitmqClusterReference:
    name:  rabbitmq-1-upstream  # Changeme: the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
  importCredentialsSecret:
    name: rabbitmq-upstream-1-secret
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-1-upstream-replicator.rabbitmq-schema-definition-sync.all
  namespace: rabbitmq-system # Changeme
spec:
  vhost: "/" # Changeme: name of a vhost
  userReference:
    name: rabbitmq-1-upstream-replicator
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq-1-upstream  # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
---
apiVersion: rabbitmq.com/v1beta1
kind: SchemaReplication
metadata:
  name: rabbitmq-1-upstream
  namespace: rabbitmq-system # Changeme
spec:
  endpoints: "172.18.205.200:5672" # Changeme
  upstreamSecret:
    name: rabbitmq-upstream-1-secret
  rabbitmqClusterReference:
    name: rabbitmq-1-upstream # Changeme: the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
---
apiVersion: rabbitmq.tanzu.vmware.com/v1beta1
kind: StandbyReplication
metadata:
  name: rabbitmq-1-upstream-configuration
  namespace: rabbitmq-system # Changeme
spec:
  operatingMode: "upstream" # has to be "upstream" to configure an upstream RabbitMQ cluster; required value
  upstreamModeConfiguration: # list of policies that Operator will create
    replicationPolicies:
      - name: replication-policy # policy name; required value
        pattern: "^.*"    # any regex expression that will be used to match quorum queues name; required value
        vhost: "/"        # Changeme: vhost name; must be an existing vhost; required value
  rabbitmqClusterReference:
    name: rabbitmq-1-upstream # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-1-upstream-replicator.defaultvhost.all
  namespace: rabbitmq-system # Changeme
spec:
  vhost: "/" # changeme: name of a vhost
  userReference: 
    name: rabbitmq-1-upstream-replicator
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq-1-upstream  # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-1-upstream-replicator
  namespace: rabbitmq-system # Changeme
spec:
  rabbitmqClusterReference:
    name:  rabbitmq-1-downstream # the downstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
  importCredentialsSecret:
    name: rabbitmq-upstream-1-secret
# ---
# apiVersion: rabbitmq.com/v1beta1
# kind: Permission
# metadata:
#   name: rabbitmq-1-upstream-replicator.rabbitmq-schema-definition-sync.all
#   namespace: rabbitmq-system # Changeme
# spec:
#   vhost: "rabbitmq_schema_definition_sync" # name of a vhost
#   userReference:
#     name: rabbitmq-1-upstream-replicator
#   permissions:
#     write: ".*"
#     configure: ".*"
#     read: ".*"
#   rabbitmqClusterReference:
#     name: rabbitmq-1-downstream  # Changeme: the downstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
# ---
# apiVersion: rabbitmq.com/v1beta1
# kind: SchemaReplication
# metadata:
#   name: downstream
#   namespace: rabbitmq-system # Changeme
# spec:
#   endpoints: "172.18.255.200:5672" # Changeme
#   upstreamSecret:
#     name: rabbitmq-upstream-1-secret
#   rabbitmqClusterReference:
#     name: rabbitmq-1-downstream  # the downstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
# ---
# ---
# apiVersion: rabbitmq.tanzu.vmware.com/v1beta1
# kind: StandbyReplication
# metadata:
#   name: downstream-configuration
#   namespace: rabbitmq-system # Changeme
# spec:
#   operatingMode: "downstream" # has to be "downstream" to configure an downstream RabbitMQ cluster
#   downstreamModeConfiguration:
#     endpoints: "172.18.255.200:5552" # Changeme: comma separated list of endpoints to the upstream RabbitMQ
#     upstreamSecret:
#       name: rabbitmq-upstream-1-secret # an existing Kubernetes secret; required value
#   rabbitmqClusterReference:
#     name: rabbitmq-1-downstream # the downstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.