apiVersion: rabbitmq.com/v1beta1
kind: SchemaReplication
metadata:
  name: rabbitmq-1-upstream-schema-replication
  namespace: rabbitmq-system
spec:
  endpoints: "172.18.255.200:5672"
  upstreamSecret:
    name: rabbitmq-upstream-1-secret
  rabbitmqClusterReference:
    name: rabbitmq-1-upstream  # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
